import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: '#f9f9fa',
        'on-background': '#1a1c1d',
        primary: '#361f1a',
        'on-primary': '#ffffff',
        'primary-container': '#4e342e',
        'on-primary-container': '#c19c94',
        'inverse-primary': '#e5beb5',
        secondary: '#5e5e5c',
        'on-secondary': '#ffffff',
        'secondary-container': '#e1dfdc',
        'on-secondary-container': '#636360',
        tertiary: '#322200',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#4e3700',
        'on-tertiary-container': '#cb9e3f',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        surface: '#f9f9fa',
        'surface-dim': '#d9dadb',
        'surface-bright': '#f9f9fa',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f3f4',
        'surface-container': '#eeeeef',
        'surface-container-high': '#e8e8e9',
        'surface-container-highest': '#e2e2e3',
        'on-surface': '#1a1c1d',
        'on-surface-variant': '#504442',
        'inverse-surface': '#2f3132',
        'inverse-on-surface': '#f0f1f2',
        outline: '#827471',
        'outline-variant': '#d4c3bf',
        'surface-tint': '#755750',
        'primary-fixed': '#ffdad2',
        'primary-fixed-dim': '#e5beb5',
        'on-primary-fixed': '#2b1611',
        'on-primary-fixed-variant': '#5c403a',
        'secondary-fixed': '#e4e2df',
        'secondary-fixed-dim': '#c8c6c4',
        'on-secondary-fixed': '#1b1c1a',
        'on-secondary-fixed-variant': '#474745',
        'tertiary-fixed': '#ffdea4',
        'tertiary-fixed-dim': '#f0bf5c',
        'on-tertiary-fixed': '#261900',
        'on-tertiary-fixed-variant': '#5d4200',
        'surface-variant': '#e2e2e3',
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        'card-gap': '20px',
        'container-padding': '32px',
        base: '8px',
        gutter: '24px'
      },
      fontFamily: {
        geist: ['Geist', 'sans-serif'],
        inter: ['Inter', 'sans-serif'],
      }
    },
  },
  plugins: [],
};
export default config;
